"""
Unsloth configuration builder.

Auto-generates optimized Unsloth FastModel training scripts.
"""

from pathlib import Path
from typing import Dict, Any, Optional

from loguru import logger
from jinja2 import Template

from ..core.schemas import ExportConfig
from ..core.exceptions import UnslothConfigError


# Unsloth training script template
UNSLOTH_TRAIN_TEMPLATE = Template('''"""
Auto-generated Unsloth training script.
Generated by Distill-Align.
"""

import torch
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# =============================================================================
# Configuration
# =============================================================================

# Model configuration
MODEL_NAME = "{{ model_name }}"
MAX_SEQ_LENGTH = {{ max_seq_length }}
DTYPE = torch.{{ dtype }}
LOAD_IN_4BIT = {{ load_in_4bit }}

# LoRA configuration
LORA_R = {{ lora_r }}
LORA_ALPHA = {{ lora_alpha }}
LORA_DROPOUT = {{ lora_dropout }}
TARGET_MODULES = {{ target_modules }}

# Training configuration
BATCH_SIZE = {{ batch_size }}
GRADIENT_ACCUMULATION_STEPS = {{ gradient_accumulation_steps }}
NUM_EPOCHS = {{ num_epochs }}
LEARNING_RATE = {{ learning_rate }}
WARMUP_STEPS = {{ warmup_steps }}
MAX_STEPS = {{ max_steps }}
OPTIMIZER = "{{ optimizer }}"
LR_SCHEDULER = "{{ lr_scheduler }}"

# Dataset configuration
DATASET_PATH = "{{ dataset_path }}"
TEXT_FIELD = "{{ text_field }}"

# Output configuration
OUTPUT_DIR = "{{ output_dir }}"

# =============================================================================
# Model Loading
# =============================================================================

print(f"Loading model: {MODEL_NAME}")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=DTYPE,
    load_in_4bit=LOAD_IN_4BIT,
)

print("Model loaded successfully")

# =============================================================================
# LoRA Configuration
# =============================================================================

print("Configuring LoRA adapters...")

model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=TARGET_MODULES,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)

print(f"LoRA configured: r={LORA_R}, alpha={LORA_ALPHA}")

# =============================================================================
# Dataset Loading
# =============================================================================

print(f"Loading dataset from: {DATASET_PATH}")

dataset = load_dataset("json", data_files=DATASET_PATH, split="train")
print(f"Dataset loaded: {len(dataset)} examples")

# =============================================================================
# Training
# =============================================================================

print("Starting training...")

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    num_train_epochs=NUM_EPOCHS,
    learning_rate=LEARNING_RATE,
    warmup_steps=WARMUP_STEPS,
    max_steps=MAX_STEPS,
    optim=OPTIMIZER,
    lr_scheduler_type=LR_SCHEDULER,
    logging_steps=10,
    save_steps=100,
    save_total_limit=3,
    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),
    seed=3407,
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field=TEXT_FIELD,
    max_seq_length=MAX_SEQ_LENGTH,
    args=training_args,
)

trainer.train()

# =============================================================================
# Save Model
# =============================================================================

print(f"Saving model to: {OUTPUT_DIR}")

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training complete!")
''')


class UnslothConfigBuilder:
    """Generates optimized Unsloth training scripts."""

    # Default LoRA target modules for common architectures
    DEFAULT_TARGET_MODULES = {
        "llama": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "mistral": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "qwen": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "phi": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        "gemma": ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    }

    def __init__(self, config: Optional[ExportConfig] = None):
        """
        Initialize the Unsloth config builder.

        Args:
            config: Optional export configuration.
        """
        self.config = config or ExportConfig()

    def generate_script(
        self,
        dataset_path: str,
        output_dir: str = "./model_output",
        **kwargs,
    ) -> Path:
        """
        Generate an Unsloth training script.

        Args:
            dataset_path: Path to the training dataset.
            output_dir: Directory for model output.
            **kwargs: Additional configuration overrides.

        Returns:
            Path to the generated script.
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        # Detect model architecture for target modules
        model_name = kwargs.get("model_name", self.config.unsloth_model)
        target_modules = self._get_target_modules(model_name)

        # Prepare template variables
        _torch_available = torch is not None
        _dtype = "bfloat16" if (_torch_available and torch.cuda.is_available() and torch.cuda.is_bf16_supported()) else "float16"

        template_vars = {
            "model_name": model_name,
            "max_seq_length": kwargs.get("max_seq_length", self.config.unsloth_max_seq_length),
            "dtype": _dtype,
            "load_in_4bit": kwargs.get("load_in_4bit", True),
            "lora_r": kwargs.get("lora_r", self.config.unsloth_lora_rank),
            "lora_alpha": kwargs.get("lora_alpha", self.config.unsloth_lora_alpha),
            "lora_dropout": kwargs.get("lora_dropout", 0.0),
            "target_modules": target_modules,
            "batch_size": kwargs.get("batch_size", 2),
            "gradient_accumulation_steps": kwargs.get("gradient_accumulation_steps", 4),
            "num_epochs": kwargs.get("num_epochs", 3),
            "learning_rate": kwargs.get("learning_rate", 2e-4),
            "warmup_steps": kwargs.get("warmup_steps", 5),
            "max_steps": kwargs.get("max_steps", -1),
            "optimizer": kwargs.get("optimizer", "adamw_8bit"),
            "lr_scheduler": kwargs.get("lr_scheduler", "linear"),
            "dataset_path": dataset_path,
            "text_field": kwargs.get("text_field", "conversations"),
            "output_dir": output_dir,
        }

        # Render template
        script_content = UNSLOTH_TRAIN_TEMPLATE.render(**template_vars)

        # Write script
        script_path = output_path / "train.py"
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script_content)

        logger.info(f"Generated Unsloth training script: {script_path}")
        return script_path

    def _get_target_modules(self, model_name: str) -> list:
        """
        Get target modules for LoRA based on model architecture.

        Args:
            model_name: Model name or path.

        Returns:
            List of target module names.
        """
        model_name_lower = model_name.lower()

        for arch, modules in self.DEFAULT_TARGET_MODULES.items():
            if arch in model_name_lower:
                return modules

        # Default to LLaMA-style modules
        return self.DEFAULT_TARGET_MODULES["llama"]

    def generate_config(self, **kwargs) -> Dict[str, Any]:
        """
        Generate configuration dictionary.

        Args:
            **kwargs: Configuration overrides.

        Returns:
            Configuration dictionary.
        """
        return {
            "model_name": kwargs.get("model_name", self.config.unsloth_model),
            "max_seq_length": kwargs.get("max_seq_length", self.config.unsloth_max_seq_length),
            "lora_r": kwargs.get("lora_r", self.config.unsloth_lora_rank),
            "lora_alpha": kwargs.get("lora_alpha", self.config.unsloth_lora_alpha),
            "load_in_4bit": kwargs.get("load_in_4bit", True),
            "batch_size": kwargs.get("batch_size", 2),
            "gradient_accumulation_steps": kwargs.get("gradient_accumulation_steps", 4),
            "num_epochs": kwargs.get("num_epochs", 3),
            "learning_rate": kwargs.get("learning_rate", 2e-4),
        }


# Import torch at module level for template rendering
try:
    import torch
except ImportError:
    torch = None
