#!/usr/bin/env python3
"""
Core Pydantic schemas for the Distill-Align framework.

These models ensure data integrity across the ingestion, synthesis, and export stages.
"""

from typing import Dict, Any, List, Literal, Optional
from pydantic import BaseModel, Field, field_validator, model_validator
import hashlib
import json
from datetime import datetime


# =============================================================================
# Ingestion Schemas
# =============================================================================

class SourceMetadata(BaseModel):
    """Metadata to preserve macro-context for each chunk."""

    source_type: Literal["pdf", "markdown", "code", "text"] = "text"
    file_path: str
    file_name: str
    title: Optional[str] = None
    author: Optional[str] = None
    language: Optional[str] = None

    # Code-specific fields
    repository_url: Optional[str] = None
    module_path: Optional[str] = None

    # Document-specific fields
    section_headers: List[str] = Field(default_factory=list)
    page_number: Optional[int] = None
    line_start: Optional[int] = None
    line_end: Optional[int] = None
    custom_tags: Dict[str, Any] = Field(default_factory=dict)


class DataChunk(BaseModel):
    """Represents a single unit of raw or processed data."""

    content: str
    metadata: SourceMetadata
    id: str = ""  # Computed in model_validator
    tokens: Optional[int] = None  # Estimated token count
    embedding: Optional[List[float]] = None  # Optional for semantic dedup

    @model_validator(mode="after")
    def _generate_id(self) -> "DataChunk":
        if not self.id:
            file_path = self.metadata.file_path if self.metadata else ""
            line_start = self.metadata.line_start if self.metadata and self.metadata.line_start else 0
            hash_input = f"{file_path}:{line_start}:{self.content[:100]}"
            self.id = hashlib.sha256(hash_input.encode()).hexdigest()[:16]
        return self

    @property
    def source_type(self) -> str:
        return self.metadata.source_type


# =============================================================================
# Synthesis Schemas
# =============================================================================

class SynthesizedTurn(BaseModel):
    """A single turn in a multi-turn conversation."""

    role: Literal["system", "user", "assistant", "tool"]
    content: str


class ConversationSchema(BaseModel):
    """A structured conversation generated by the Socratic Transformer."""

    id: str  # UUID or deterministic hash
    source_chunk_id: str
    turns: List[SynthesizedTurn]
    reasoning_trace: Optional[str] = None  # Captured deep thinking
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0)

    def get_system_prompt(self) -> Optional[str]:
        """Extract system prompt if present."""
        for turn in self.turns:
            if turn.role == "system":
                return turn.content
        return None

    def get_user_turns(self) -> List[SynthesizedTurn]:
        """Extract all user turns."""
        return [t for t in self.turns if t.role == "user"]

    def get_assistant_turns(self) -> List[SynthesizedTurn]:
        """Extract all assistant turns."""
        return [t for t in self.turns if t.role == "assistant"]


# =============================================================================
# Export Schemas
# =============================================================================

class ShareGPTMessage(BaseModel):
    """Standard ShareGPT format message."""

    from_: Literal["human", "gpt", "system", "tool"] = Field(..., alias="from")
    value: str

    model_config = {"populate_by_name": True}


class ShareGPTItem(BaseModel):
    """A single ShareGPT conversation item."""

    id: str
    conversations: List[ShareGPTMessage]


class AlpacaEntry(BaseModel):
    """Standard Alpaca format entry."""

    instruction: str
    input: str
    output: str
    system: Optional[str] = None

    @field_validator("system", mode="before")
    @classmethod
    def _empty_system_to_none(cls, v: Optional[str]) -> Optional[str]:
        if v == "":
            return None
        return v


# =============================================================================
# Configuration Schemas
# =============================================================================

class IngestionConfig(BaseModel):
    """Configuration for the ingestion pipeline."""

    chunk_size: int = Field(default=1000, ge=1)
    chunk_overlap: int = Field(default=200, ge=0)
    respect_headers: bool = True  # For markdown/code
    max_chunk_tokens: int = Field(default=4000, ge=1)
    include_metadata: bool = True


class SynthesisConfig(BaseModel):
    """Configuration for the synthesis pipeline."""

    llm_provider: Literal["openai", "ollama", "vllm"] = "openai"
    model_name: str = "gpt-4o"
    base_url: Optional[str] = None
    api_key: Optional[str] = None
    max_concurrency: int = Field(default=5, ge=1)
    max_rpm: int = Field(default=60, ge=1)
    retry_attempts: int = Field(default=5, ge=1)
    temperature: float = Field(default=0.7, ge=0.0, le=2.0)
    socratic_enabled: bool = True
    scaffold_enabled: bool = True


class ExportConfig(BaseModel):
    """Configuration for the export pipeline."""

    formats: List[Literal["sharegpt", "alpaca"]] = Field(default=["sharegpt"])
    output_dir: str = "./output"
    generate_unsloth_script: bool = True
    unsloth_model: str = "unsloth/Meta-Llama-3.1-8B-Instruct"
    unsloth_max_seq_length: int = 2048
    unsloth_lora_rank: int = 16
    unsloth_lora_alpha: int = 16


class AppConfig(BaseModel):
    """Top-level application configuration."""

    ingestion: IngestionConfig = Field(default_factory=IngestionConfig)
    synthesis: SynthesisConfig = Field(default_factory=SynthesisConfig)
    export: ExportConfig = Field(default_factory=ExportConfig)
    log_level: str = "INFO"
    cache_dir: str = ".cache"
